spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: amanjain
    password: mydatabase
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
